AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - spec/*
    - ms_teams.gemspec

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
